# Generated by Django 3.0.5 on 2020-05-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_axfuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axfuser',
            name='u_icon',
            field=models.ImageField(upload_to='icon/%Y/%m/%d/'),
        ),
    ]
