# Generated by Django 3.0.5 on 2020-05-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_foodtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtype',
            old_name='typenames',
            new_name='typename',
        ),
    ]
