# Generated by Django 3.0.5 on 2020-05-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20200516_1057'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodtype',
            table='axf_foodtype',
        ),
    ]
