# Generated by Django 3.0.5 on 2020-05-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_goods_productid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='price',
            new_name='marketprice',
        ),
    ]
