# Generated by Django 3.0.5 on 2020-05-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20200516_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
