# Generated by Django 3.0.5 on 2020-05-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_order_ordergoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axfuser',
            name='u_email',
            field=models.CharField(max_length=64),
        ),
    ]
